ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_images" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- Postgres exempts a table's owner from RLS by default, and our app
-- connects as the owning role (neondb_owner) — without FORCE, the policies
-- above would silently do nothing for every query this app makes. Not
-- generated by drizzle-kit; added by hand, see docs/DATA_MODEL.md §5.
ALTER TABLE "orders" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_images" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "products" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "orders" AS PERMISSIVE FOR ALL TO public USING (vendor_id = current_setting('app.vendor_id')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "product_images" AS PERMISSIVE FOR ALL TO public USING (vendor_id = current_setting('app.vendor_id')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "products" AS PERMISSIVE FOR ALL TO public USING (vendor_id = current_setting('app.vendor_id')::uuid);